### ISSUE TITLE
Support CircleCI Enterprise Server

### ISSUE THREAD

**Issue by teppeis** [worldturtlemedia/circleci-api#236]
Currently, the endpoint is hard coded.
https://github.com/worldturtlemedia/circleci-api/blob/0ab4f1c8e95282bb5c36e529a0fc26931e401cce/src/types/lib.ts#L1

To support self-hosted CircleCI Enterprise server, please provide an option to specify the endpoint.

**Comment by jordond** [comment]
Excellent idea!  I'll add that option.

**Comment by teppeis** [comment]
awesome!
