### ISSUE TITLE
Set user-agent string

### ISSUE THREAD

**Issue by marcomorain** [worldturtlemedia/circleci-api#673]
Hi there,

Thanks for making this project 👍 

I'm an engineer at CircleCI, and my team have recently been working on API new improvements to our API (support for contexts, approval jobs), as well looking at API usage, and adding rate limits.

I would be really helpful to us if this project could set a User Agent to identify itself, so that we can see where our traffic is coming from and how folks. Currently requests have a user agent set by axios (like `axios/0.19.0`).

If you could set a user agent like `worldtutlemedia/circleci-api x.y.z`, that would really help us out 👍 

Thanks again for working on this project.

Marc

**Comment by jordond** [comment]
I'll add that as soon as I get a second :+1:

**Comment by marcomorain** [comment]
Thanks so much @jordond  🙏 I really appreciate it.

**Comment by jordond** [comment]
Look's like `semantic-release` crapped out and couldn't update this issue. But a new version has been published with this fix :+1:
