### ISSUE TITLE
Typings are pointing to a wrong location

### ISSUE THREAD

**Issue by jurijzahn8019** [worldturtlemedia/circleci-api#718]
Hi,

In the package json

the typings location is: `"typings": "dist/types/index.d.ts"`

But in the published package it is `dist/types/src/index.d.ts`

This breaks the build process.

![image](https://user-images.githubusercontent.com/44019949/91342766-cc51fa00-e7db-11ea-96ca-1832848f06ce.png)

Package Version: 4.1.1
Working Version: 4.0.0

**Comment by jordond** [comment]
Thanks! Good catch, I have updated the path in the `package.json` and it should be released shortly.
