### ISSUE TITLE
Workflows are not an array, eventhough the name sounds like that. 

### ISSUE THREAD

**Issue by andreasmarkussen** [worldturtlemedia/circleci-api#786]
https://github.com/worldturtlemedia/circleci-api/blob/2f9509aa6bc7c32dad18a9845f42f3305b74b63d/src/types/api.ts#L490

I can see that both in the documentation and in the responses that I get returned. 

https://circleci.com/docs/api/#recent-builds-for-a-single-project

**Comment by jordond** [comment]
I open to PR's if you want to fix that!

If not I can try to find some time in the next couple days.

**Comment by andreasmarkussen** [comment]
On it :)

**Comment by andreasmarkussen** [comment]
PR Added
